spring:
  spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: spring
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect